
"use client";

import type { Metadata } from "next";
import { League_Spartan, Poppins } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@emotion/react";
import theme from "@/theme";
import CssBaseline from "@mui/material/CssBaseline";

const LeagueSpartan = League_Spartan({
  variable: "--font-league-spartan",
  subsets: ["latin"],
});

const PoppinsM = Poppins({
  weight: ["400", "700"],
  variable: "--font-poppins-mono",
  subsets: ["latin"],
});



// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${LeagueSpartan.variable} ${PoppinsM.variable} antialiased`}
        suppressHydrationWarning
      >
        <ThemeProvider theme={theme}>
          <CssBaseline />
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
